### ISSUE TITLE
Why always in initializing?

### ISSUE THREAD

**Issue by cyxnzb** [HFAiLab/jupyterlab_tensorboard_pro#10]
tensorboard                    2.10.1
tensorboard-data-server        0.6.1
tensorboard-plugin-wit         1.8.1
tensorflow                     2.10.0
tensorflow-estimator           2.10.0
tensorflow-gpu                 2.10.0
tensorflow-io-gcs-filesystem   0.27.0

In JupyterLab from KubeFlow,When i open Tensorboard,it always in initializing

**Comment by aircloud** [comment]
The most likely cause for this problem is that the backend of `jupyterlab-tensorboard-pro` has not been successfully installed
Or didn't find it in the KubeFlow environment. (Actually I didn't use it in KubeFlow before)

Some ideas:

* try `import jupyterlab_tensorboard_pro` in jupyterlab terminal to check if it is found
* use --debug to start jupyter, and search `jupyterlab_tensorboard_pro` in stdout to find some error message

I'll see if I can find a kubeflow environment to try this weekend

**Comment by cyxnzb** [comment]
> The most likely cause for this problem is that the backend of `jupyterlab-tensorboard-pro` has not been successfully installed Or didn't find it in the KubeFlow environment. (Actually I didn't use it in KubeFlow before)
> 
> Some ideas:
> 
> * try `import jupyterlab_tensorboard_pro` in jupyterlab terminal to check if it is found
> * use --debug to start jupyter, and search `jupyterlab_tensorboard_pro` in stdout to find some error message
> 
> I'll see if I can find a kubeflow environment to try this weekend

Can u speak Chinese?
I can import jupyterlab_tensorboard_pro with no error,but i can't open jupyterlab tensorboard pro,and i think it is difficult for me to start jupyter again in the kubeflow.

如果你能看懂中文的话，我是在[[](url)](https://github.com/tencentmusic/cube-studio/)  这个平台下使用的tensorboard-pro,具体复现过程：
部署完这个平台后，在“在线开发”、“代码开发”的notebook模块下，新建了一个notebook,镜像选取的是“notebook:jupyter-ubuntu-cpu-base”，然后安装咱们的tensorboard pro，之后能看到tensorboard pro模块，但打不开

**Comment by cyxnzb** [comment]
i see the log in Dashboard:
W 2022-10-11 17:42:47.343 ServerApp] 404 GET /notebook/jupyter/admin-eda9/api/tensorboard_pro?1665481364997 (10.42.0.100) 2.30ms referer=http://tcloud.com/notebook/jupyter/admin-eda9/lab/tree/competition/Third

**Comment by aircloud** [comment]
从以上信息来看，确实是后端部分没有安装成功。

实际上，这类 jupyter 插件后端安装成功后，一般会有两个内容：

1. 配置文件，在 `etc/jupyter/jupyter_server_config.d/jupyterlab_tensorboard_pro.json`，jupyter 后端会自动读取 `etc/jupyter` 这里的配置文件，来尝试加载插件，里面的内容：

```
{
  "ServerApp": {
    "jpserver_extensions": {
      "jupyterlab_tensorboard_pro": true
    }
  }
}
```


2. python 包，路径在 `lib/python3.8/site-packages/jupyterlab_tensorboard_pro`

如果是我们自己 python 环境安装的话，这样就够了。

从你这里的情况来看，可能是:

1. 配置文件没有正确写入
2. 不过更可能是**你在 jupyterlab 启动之后安装的插件，这个时候其实已经晚了**，看看能不能持久化之后重启一下。

我看了下这个平台，目前我这里部署的话可能会面临一些问题，我之后再关注试试看，不过你可以先看看是不是我上面猜想的原因

**Comment by cyxnzb** [comment]
> 从以上信息来看，确实是后端部分没有安装成功。
> 
> 实际上，这类 jupyter 插件后端安装成功后，一般会有两个内容：
> 
> 1. 配置文件，在 `etc/jupyter/jupyter_server_config.d/jupyterlab_tensorboard_pro.json`，jupyter 后端会自动读取 `etc/jupyter` 这里的配置文件，来尝试加载插件，里面的内容：
> 
> ```
> {
>   "ServerApp": {
>     "jpserver_extensions": {
>       "jupyterlab_tensorboard_pro": true
>     }
>   }
> }
> ```
> 
> 2. python 包，路径在 `lib/python3.8/site-packages/jupyterlab_tensorboard_pro`
> 
> 如果是我们自己 python 环境安装的话，这样就够了。
> 
> 从你这里的情况来看，可能是:
> 
> 1. 配置文件没有正确写入
> 2. 不过更可能是**你在 jupyterlab 启动之后安装的插件，这个时候其实已经晚了**，看看能不能持久化之后重启一下。
> 
> 我看了下这个平台，目前我这里部署的话可能会面临一些问题，我之后再关注试试看，不过你可以先看看是不是我上面猜想的原因

明白了，不过还好这个平台上已经有镜像包含您的这个插件了，然后也可以正常使用了，但是我本地环境测试安装又出现这个问题了，我估计是在jupyterlab启动后安装造成的，回头我再试试看，谢谢解答！

**Comment by aircloud** [comment]
这个问题的平台我后续继续关注一下，然后现在既然正常使用了这个 issue 我就先关闭了

**Comment by cyxnzb** [comment]
> 这个问题的平台我后续继续关注一下，然后现在既然正常使用了这个 issue 我就先关闭了

好滴，谢谢啦
