### ISSUE TITLE
Click "TensorBoard" in Launcher should launch new instance instead of re-opening previous instance

### ISSUE THREAD

**Issue by huweiATgithub** [HFAiLab/jupyterlab_tensorboard_pro#13]
To reproduce:
1. navigate to any folder and launch Tensorboard from JupyterLab Launcher.
2. navigate to another folder and click Tensorboard from Launcher
Behavior:
the second click of "Tensorboard" just focus back to the previous TensorBoard tab.

I think it is better to create a new tab with a new instance after every click on the Tensorboard button.
- it is intuitive that in Launcher, clicking on every button will launch something
- Launcher works well with the File browser. Navigating in Lab's File Browser and creating something from the launcher is quite convenient. Currently, we need to manually type in the logs directory to launch a second Tensorboar instance.

**Comment by aircloud** [comment]
Thank you. Your suggestion is reasonable

I will consider to modify the implementation here and adding a configuration option this weekend.

>In fact, the reason why reuse was that the Tensorboard itself will cause additional consumption, and users are likely to ignore the opened Tensorboard

**Comment by huweiATgithub** [comment]
In the current implementation, the `Tensorboard` button in the launcher does not directly start a Tensorboard instance: 
![image](https://user-images.githubusercontent.com/37072526/203160596-82fb67be-2fbd-41b4-8fee-33859532fbdd.png)
But instead, it opens a tab with the `Log Dir` filled. 
Then the user may choose to create an instance or not.

So I think your consideration of resource consumption is not a severe problem. 

I guess on the `Tensorboard` button click, we may
- if there is no running instance, keep the current implementation.
- if there is another instance, but with a different log dir, we may open a **new** tab with the current path filled in as the image shows:
![image](https://user-images.githubusercontent.com/37072526/203161629-965fa912-f9e5-41b2-a8bc-16f5b308e3f1.png)
- if there is another instance whose log dir is the same as the current dir, we may navigate to that tab (if it is active).

**new** tab: If a user launches a Tensorboard instance in another folder, he may want a new tab showing that.

What's your idea on that?

**Comment by aircloud** [comment]
It's reasonable and It's basically the same as my idea. 
I'm trying to change this logic.

**Comment by aircloud** [comment]
> In the current implementation, the `Tensorboard` button in the launcher does not directly start a Tensorboard instance: ![image](https://user-images.githubusercontent.com/37072526/203160596-82fb67be-2fbd-41b4-8fee-33859532fbdd.png) But instead, it opens a tab with the `Log Dir` filled. Then the user may choose to create an instance or not.
> 
> So I think your consideration of resource consumption is not a severe problem.
> 
> I guess on the `Tensorboard` button click, we may
> 
> * if there is no running instance, keep the current implementation.
> * if there is another instance, but with a different log dir, we may open a **new** tab with the current path filled in as the image shows:
>   ![image](https://user-images.githubusercontent.com/37072526/203161629-965fa912-f9e5-41b2-a8bc-16f5b308e3f1.png)
> * if there is another instance whose log dir is the same as the current dir, we may navigate to that tab (if it is active).
> 
> **new** tab: If a user launches a Tensorboard instance in another folder, he may want a new tab showing that.
> 
> What's your idea on that?

Thank you for your very useful suggestions. I have basically made adjustments according to this logic. If there are any questions about it later, we can continue to discuss it
