### ISSUE TITLE
404 GET /api/tensorboard_pro

### ISSUE THREAD

**Issue by elch10** [HFAiLab/jupyterlab_tensorboard_pro#14]
I'm getting such error
```
[W 16:29:50.918 NotebookApp] 404 GET /api/tensorboard_pro?1669814990914 (172.17.0.1) 1.540000ms referer=http://localhost:8888/lab
```
Environment
```
          conda version : 4.12.0
         python version : 3.9.15.final.0
tensorboard==2.11.0
tensorflow==2.11.0
tensorflow-estimator==2.11.0
jupyterlab-tensorboard-pro==0.4.0
jupyter==1.0.0
jupyterlab==3.5.0
```
Developer console error
<img width="666" alt="image" src="https://user-images.githubusercontent.com/15147137/204810428-1205600a-28cb-456c-8537-c5ccc3a97745.png">

When I open tensorboard from launcher - I just see `Initializing`
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/15147137/204811258-6712ab6f-b959-41e5-b1c9-4e22ec21c311.png">

How can I debug?

**Comment by elch10** [comment]
When run jupyter with `--debug`, I see only such messages about tensorboard_pro
```
[D 16:39:35.296 NotebookApp] Path jupyterlab_tensorboard_pro/static/184.079d3e4ea819d1120b64.js served from /home/user/conda/share/jupyter/labextensions/jupyterlab_tensorboard_pro/static/184.079d3e4ea819d1120b64.js
[D 16:39:35.297 NotebookApp] 304 GET /lab/extensions/jupyterlab_tensorboard_pro/static/184.079d3e4ea819d1120b64.js?v=079d3e4ea819d1120b64 (172.17.0.1) 2.390000ms
[D 16:39:35.298 NotebookApp] Path jupyterlab_tensorboard_pro/static/674.332b94913cec73e4842b.js served from /home/user/conda/share/jupyter/labextensions/jupyterlab_tensorboard_pro/static/674.332b94913cec73e4842b.js
[D 16:39:35.299 NotebookApp] 304 GET /lab/extensions/jupyterlab_tensorboard_pro/static/674.332b94913cec73e4842b.js?v=332b94913cec73e4842b (172.17.0.1) 3.600000ms
[D 16:39:35.302 NotebookApp] Path jupyterlab_tensorboard_pro/static/445.f4d009ce820e01bc9e3a.js served from /home/user/conda/share/jupyter/labextensions/jupyterlab_tensorboard_pro/static/445.f4d009ce820e01bc9e3a.js
[D 16:39:35.303 NotebookApp] 304 GET /lab/extensions/jupyterlab_tensorboard_pro/static/445.f4d009ce820e01bc9e3a.js?v=f4d009ce820e01bc9e3a (172.17.0.1) 3.440000ms
[D 16:39:35.308 NotebookApp] Path jupyterlab_tensorboard_pro/static/924.674ec90e4b9213b8c1c9.js served from /home/user/conda/share/jupyter/labextensions/jupyterlab_tensorboard_pro/static/924.674ec90e4b9213b8c1c9.js
[D 16:39:35.309 NotebookApp] 304 GET /lab/extensions/jupyterlab_tensorboard_pro/static/924.674ec90e4b9213b8c1c9.js?v=674ec90e4b9213b8c1c9 (172.17.0.1) 4.970000ms
```

**Comment by aircloud** [comment]
I tried the same version of the dependencies, and it works. The main reason for staying in the initialization is that the plug-in backend cannot be found 
Therefore, need your some help to continue positioning.

you can try:

```
PYTHONDIR=$(dirname `which python`)/../
```

1. find if the path exists:  `$PYTHONDIR/etc/jupyter/jupyter_server_config.d/jupyterlab_tensorboard_pro.json`

and the content should be:

```
{
  "ServerApp": {
    "jpserver_extensions": {
      "jupyterlab_tensorboard_pro": true
    }
  }
}
```

2. find if the path exists:  `$PYTHONDIR/lib/python3.9/site-packages/jupyterlab_tensorboard_pro`,  There are some python files that should be in this:

```
__init__.py            __pycache__            api_handlers.py        handlers.py            labextension           tensorboard_manager.py
```

3. find if there is a log like (or some other errors) where run jupyter-lab:

```
[I 2022-09-17 17:52:08.559 ServerApp] jupyterlab_tensorboard_pro | extension was successfully linked.
```

**Comment by elch10** [comment]
Steps about `PYTHONDIR` is ok
```bash
jovyan@075b9b2634d7:~$ export PYTHONDIR=$(dirname `which python`)/../
jovyan@075b9b2634d7:~$ echo $PYTHONDIR/
/home/user/conda/bin/..//
jovyan@075b9b2634d7:~$ cat $PYTHONDIR/etc/jupyter/jupyter_server_config.d/jupyterlab_tensorboard_pro.json
{
  "ServerApp": {
    "jpserver_extensions": {
      "jupyterlab_tensorboard_pro": true
    }
  }
}
jovyan@075b9b2634d7:~$ ls $PYTHONDIR/lib/python3.9/site-packages/jupyterlab_tensorboard_pro
__init__.py  __pycache__  api_handlers.py  handlers.py	labextension  tensorboard_manager.py
```

But now I found error. If I run `jupyter notebook` and open link, when at the end added `/lab` (i.e. `localhost:8888/lab`) - it won't work. But If I just start `jupyter lab` - thats ok. Can we fix `jupyter_tensorboard_pro` for `jupyter lab`, that are run from `jupyter notebook`?

**Comment by aircloud** [comment]
I understand, it should be a problem of starting with `jupyter notebook`

Because this plugin was originally prepared for jupyterlab, using `jupyter notebook` will not start the corresponding plugin backend

Here I am continuing to look at whether it can support the use of `jupyter notebook` to start

**Comment by aircloud** [comment]
supported (0.5.0)
