### ISSUE TITLE
Start TensorBoard internal error

### ISSUE THREAD

**Issue by liyuechen1999** [HFAiLab/jupyterlab_tensorboard_pro#16]
点击 Create Tensorboard 后显示Start TensorBoard internal error

**Comment by aircloud** [comment]
这个一般是 tensorboard 后端初始化报错了，我建议：

1.  F12 打开控制台，Network 面板搜索 tensorboard，查看报错信息
2. 从 jupyterlab 的标注输出中看看有没有什么报错信息

可以贴一下相关报错我们看看

**Comment by liyuechen1999** [comment]
升级了jupyterlab后就不报错了
