### ISSUE TITLE
Upgrade to support JupyterLab 4.x

### ISSUE THREAD

**Issue by twalcari** [HFAiLab/jupyterlab_tensorboard_pro#19]
This extension needs to be upgraded to work with JupyterLab 4.x

Upgrade guide is here: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#jupyterlab-3-x-to-4-x

**Comment by xiaolao** [comment]
有计划什么时候兼容下 jupyterlab 4.x 吗？

**Comment by cyxnzb** [comment]
4.x提示Cannot read properties of undefined (reading 'model')

**Comment by octavd** [comment]
Hello,

Looking forward for the jupyterlab 4.x compatibility.

**Comment by aircloud** [comment]
目前计划十一期间测试升级下。

**Comment by cyxnzb** [comment]
> 目前计划十一期间测试升级下。

好滴，辛苦了

**Comment by aircloud** [comment]
try 4.0.0 for jupyterlab 4.x
new issue if has any problems
