### ISSUE TITLE
[Enhancement] Support s3 path as logdir

### ISSUE THREAD

**Issue by jiyuanq** [HFAiLab/jupyterlab_tensorboard_pro#2]
Currently logdir is assumed to be a local FS path, but in a lot of cases, for example with distributed training, we may write tensorboard logs to s3.
Can we add support for passing s3 path as logdir and also make tensorboard capable of loading from s3 (by importing tensorflow_io)?

**Comment by aircloud** [comment]
Thank you for your suggestion, I think it does make some sense.

I'll look into it this week and come up with an update plan.

**Comment by jiyuanq** [comment]
Thanks! I think this feature could be really helpful

**Comment by aircloud** [comment]
After a simple modification, the s3 path is now supported, and the README has been [updated](https://github.com/HFAiLab/jupyterlab_tensorboard_pro#use-aws-s3)

In addition, I think some loading experience of tensorboard is not very good, I will continue to see how to optimize it later
